runmode: debug                # 开发模式, debug, release, test
addr: :4990              # HTTP绑定端口
name: videoserver             # API Server的名字
url: http://127.0.0.1:4990  # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
app:
  page_size: 10
  team_count: 12
  machine_id: 192168100101
file:
  img_path: /home/yjh/projects/Tally/static_file
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key

log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
  info:
    writers: file,stdout
    logger_level: DEBUG
    logger_file: log/info.log
    log_format_text: true
    rollingPolicy: size
    log_rotate_date: 1
    log_rotate_size: 1
    log_backup_count: 7
db:
  name: im
  addr: 127.0.0.1:3306
  username: root
  password: root
docker_db:
  name: im
  addr: 127.0.0.1:3306
  username: root
  password: root

redis:
  address: 127.0.0.1
  port: 6379

nats:
  cluster_id: test-cluster
  client_id: test-client
  url: nats://127.0.0.1:4222